global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['paygate-posportal-db:3306']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: 'paygate-posportal-db:9104'
